import {test,expect} from '@playwright/test';
async function setup(page){await page.route('**/2_3DSimulation/main.js*',async route=>{const response=await route.fetch();await route.fulfill({response,body:`${await response.text()}\nwindow.__beltUi={state,createPrimitiveShapeRoot,updateUIStatus,equipmentApp,ensureWorkspaceModelId,getImportedModelParts,writeOlpAddress};`});});await page.goto('/2_3DSimulation/index.html');await page.waitForFunction(()=>window.__beltUi);await page.evaluate(()=>{const a=window.__beltUi;for(const [name,dimensions,xyz]of [['컨베이어',{x:800,y:160,z:30},[0,0,0]],['이송 물체',{x:40,y:40,z:40},[-200,0,30]]]){const m=a.createPrimitiveShapeRoot('box',dimensions,{name});m.position.fromArray(xyz);a.state.scene.add(m);a.state.models.push(m);}a.equipmentApp.save({id:'belt-object',type:'OBJECT',movingRef:'equipment-model:'+a.ensureWorkspaceModelId(a.state.models[1])+'/-1'});a.updateUIStatus();});await page.locator('button[data-model-tree-id]').filter({hasText:'컨베이어'}).click({button:'right'});await page.locator('#model-motion-settings').click();}
test('동작 부품 선택 중 모델 트리에서 클릭하면 해당 부품이 설정에 추가된다',async({page})=>{await setup(page);await page.locator('[data-equipment-role="movingRef"] button').click();await page.locator('button[data-model-tree-id]').filter({hasText:'이송 물체'}).click();await expect(page.locator('[data-equipment-role="movingRef"] input:checked')).toHaveCount(2);});
test('컨베이어 설정은 IO 없이 시험하고 IO 연결 후에도 운전하며 모델 트리에서 다시 편집한다',async({page})=>{await setup(page);await page.locator('#equipment-form [name="type"]').selectOption('CONVEYOR');await page.locator('#equipment-form button[type="submit"]').click();await expect(page.locator('#equipment-error')).toContainText('저장');await page.locator('[data-conveyor-command="FORWARD"]').click();await expect.poll(()=>page.evaluate(()=>window.__beltUi.state.models[1].position.x)).toBeGreaterThan(-190);await page.locator('[data-conveyor-command="STOP"]').click();const stopped=await page.evaluate(()=>window.__beltUi.state.models[1].position.x);await page.waitForTimeout(120);expect(await page.evaluate(()=>window.__beltUi.state.models[1].position.x)).toBeCloseTo(stopped,6);await page.locator('#equipment-form [name="forwardAddress"]').fill('600');await page.locator('#equipment-form button[type="submit"]').click();await expect(page.locator('#equipment-error')).toContainText('저장');await page.locator('#equipment-close').click();await page.evaluate(()=>window.__beltUi.writeOlpAddress('Out[600]',1));await expect.poll(()=>page.evaluate(()=>window.__beltUi.state.models[1].position.x)).toBeGreaterThan(stopped+10);await page.locator('button[data-model-tree-id]').filter({hasText:'컨베이어'}).click({button:'right'});await page.locator('#model-motion-settings').click();await expect(page.locator('#equipment-form [name="type"]')).toHaveValue('CONVEYOR');await expect(page.locator('#equipment-form [name="forwardAddress"]')).toHaveValue('600');});


test('조립 모델에서 벨트 부품을 선택하면 가이드를 제외한 벨트 상면의 물체만 이송한다',async({page})=>{
 await setup(page);await page.locator('#equipment-close').click();
 await page.evaluate(()=>{const a=window.__beltUi,belt=a.state.models[0],part=belt.children.find(child=>child.isMesh);part.userData.modelPartName='벨트 면';part.userData.modelPartId='belt-face';const guide=a.createPrimitiveShapeRoot('box',{x:800,y:10,z:100},{name:'가이드'});guide.position.set(0,70,30);belt.add(guide);guide.userData.modelPartName='높은 가이드';guide.userData.modelPartId='belt-guide';belt.userData.importedParts=[part,guide];delete belt.userData.primitiveShape;belt.userData.uploaded=true;a.updateUIStatus();});
 await page.locator('button[data-model-tree-id]').filter({hasText:'컨베이어'}).click({button:'right'});await page.locator('#model-motion-settings').click();await page.locator('#equipment-form [name="type"]').selectOption('CONVEYOR');await page.locator('[data-equipment-role="movingRef"] button').click();await page.locator('button[data-model-part-id]').filter({hasText:'벨트 면'}).click();
 await expect(page.locator('[data-equipment-role="movingRef"] input:checked')).toHaveCount(1);await expect(page.locator('[data-equipment-role="movingRef"] input:checked')).toHaveValue(/\/0$/);
 await page.locator('#equipment-form button[type="submit"]').click();await expect(page.locator('#equipment-error')).toContainText('저장');await page.locator('[data-conveyor-command="FORWARD"]').click();await expect.poll(()=>page.evaluate(()=>window.__beltUi.state.models[1].position.x)).toBeGreaterThan(-190);expect(await page.evaluate(()=>window.__beltUi.state.models[0].position.x)).toBe(0);
});
