import {test,expect} from '@playwright/test';
test('충돌은 로봇 하위 모델만 감지하고 고정 설비와 Tool·오브젝트 조합은 제외한다',async({page})=>{
 const errors=[];page.on('pageerror',e=>errors.push(e.message));await page.route('**/2_3DSimulation/main.js*',async route=>{const response=await route.fetch();await route.fulfill({response,body:await response.text()+'\nwindow.__collisionScope={state,equipmentApp,THREE,createPrimitiveShapeRoot,ensureWorkspaceModelId,getRobotToolMountFrame,checkSceneCollisions,createAutoPathCollisionEvaluator};'});});await page.goto('/2_3DSimulation/index.html');await page.waitForFunction(()=>window.__collisionScope);await page.locator('#model-select').selectOption('robot:IR-R10H-120');await page.waitForFunction(()=>window.__collisionScope.state.models.some(m=>m.userData.tcpFrame));
 const pairs=await page.evaluate(()=>{
  const a=window.__collisionScope,robot=a.state.models.find(m=>m.userData.tcpFrame),frame=a.getRobotToolMountFrame(robot);
  const box=(name,x,placement)=>{const m=a.createPrimitiveShapeRoot('box',{x:30,y:30,z:30},{name});m.position.set(x,0,0);a.state.scene.add(m);a.state.models.push(m);if(placement){frame.attach(m);m.userData.attachmentHost=robot;m.userData.placement=placement;}return m;};
  const ref=m=>'equipment-model:'+a.ensureWorkspaceModelId(m)+'/-1';
  box('고정 베이스',5000);box('고정 모듈',5000);box('검사 Tool',10000,'tcp');box('Tool 장애물',10000);box('흡착 Tool',11000,'tcp');const free=box('Tool 접촉 오브젝트',11000),held=box('붙은 오브젝트',12000),other=box('다른 오브젝트',12000),heldObstacle=box('이송 오브젝트',13000);box('오브젝트 장애물',13000);
  a.equipmentApp.save({id:'collision-objects',type:'OBJECT',movingRefs:[free,held,other,heldObstacle].map(ref)});for(const m of [held,heldObstacle]){frame.attach(m);m.userData.attachmentHost=robot;m.userData.placement='grip-object';}box('부분 등록 Tool',14000,'tcp');const assembly=box('부분 등록 조립품',14000);assembly.clear();delete assembly.userData.primitiveShape;assembly.userData.uploaded=true;const part=a.createPrimitiveShapeRoot('box',{x:30,y:30,z:30},{name:'등록 부품'}),fixed=a.createPrimitiveShapeRoot('box',{x:30,y:30,z:30},{name:'고정 부품'});assembly.add(part,fixed);assembly.userData.importedParts=[part,fixed];a.equipmentApp.save({id:'partial-collision-object',type:'OBJECT',movingRef:'equipment-model:'+a.ensureWorkspaceModelId(assembly)+'/0'});a.state.collision.enabled=true;
  const names=hits=>hits.map(hit=>[hit.objectA.userData.modelName,hit.objectB.userData.modelName].sort().join(' / '));return {scene:names(a.checkSceneCollisions({force:true})),planning:names(a.createAutoPathCollisionEvaluator(robot,robot.userData.joints.map(j=>j.angle)).getHits(robot.userData.joints.map(j=>j.angle)))};
 });expect(pairs.planning.sort()).toEqual(pairs.scene.sort());const hits=pairs.scene;expect(hits).toHaveLength(3);expect(hits.some(p=>p.includes('부분 등록 Tool')&&p.includes('부분 등록 조립품'))).toBe(true);expect(hits.some(p=>p.includes('검사 Tool')&&p.includes('Tool 장애물'))).toBe(true);expect(hits.some(p=>p.includes('이송 오브젝트')&&p.includes('오브젝트 장애물'))).toBe(true);expect(errors).toEqual([]);
});
